version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  mango:
    image: nikitaevs/mango
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: