name: unit_test

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get install python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: TestAndCoverage
        run: |
          coverage run manage.py test
          coverage report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}